src/Presentation/Nop.Web/Areas/Admin/Controllers/RecurringPaymentController.cs
using System;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Nop.Services.Localization;
using Nop.Services.Messages;
using Nop.Services.Orders;
using Nop.Services.Security;
using Nop.Web.Areas.Admin.Factories;
using Nop.Web.Areas.Admin.Infrastructure.Mapper.Extensions;
using Nop.Web.Areas.Admin.Models.Orders;
using Nop.Web.Framework.Controllers;
using Nop.Web.Framework.Mvc.Filters;

namespace Nop.Web.Areas.Admin.Controllers
{
    public partial class RecurringPaymentController : BaseAdminController
    {
        #region Fields

        private readonly ILocalizationService _localizationService;
        private readonly INotificationService _notificationService;
        private readonly IOrderProcessingService _orderProcessingService;
        private readonly IOrderService _orderService;
        private readonly IPermissionService _permissionService;
        private readonly IRecurringPaymentModelFactory _recurringPaymentModelFactory;

        #endregion Fields

        #region Ctor

        public RecurringPaymentController(ILocalizationService localizationService,
            INotificationService notificationService,
            IOrderProcessingService orderProcessingService,
            IOrderService orderService,
            IPermissionService permissionService,
            IRecurringPaymentModelFactory recurringPaymentModelFactory)
        {
            _localizationService = localizationService;
            _notificationService = notificationService;
            _orderProcessingService = orderProcessingService;
            _orderService = orderService;
            _permissionService = permissionService;
            _recurringPaymentModelFactory = recurringPaymentModelFactory;
        }

        #endregion

        #region Methods

        public virtual IActionResult Index()
        {
            return RedirectToAction("List");
        }

        public virtual IActionResult List()
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageRecurringPayments))
                return AccessDeniedView();

            //prepare model
            var model = _recurringPaymentModelFactory.PrepareRecurringPaymentSearchModel(new RecurringPaymentSearchModel());

            return View(model);
        }

        [HttpPost]
        public virtual IActionResult List(RecurringPaymentSearchModel searchModel)
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageRecurringPayments))
                return AccessDeniedDataTablesJson();

            //prepare model
            var model = _recurringPaymentModelFactory.PrepareRecurringPaymentListModel(searchModel);

            return Json(model);
        }

        public virtual IActionResult Edit(int id)
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageRecurringPayments))
                return AccessDeniedView();

            //try to get a recurring payment with the specified id
            var payment = _orderService.GetRecurringPaymentById(id);
            if (payment == null || payment.Deleted)
                return RedirectToAction("List");

            //prepare model
            var model = _recurringPaymentModelFactory.PrepareRecurringPaymentModel(null, payment);

            return View(model);
        }

        [HttpPost, ParameterBasedOnFormName("save-continue", "continueEditing")]
        [FormValueRequired("save", "save-continue")]
        public virtual IActionResult Edit(RecurringPaymentModel model, bool continueEditing)
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageRecurringPayments))
                return AccessDeniedView();

            //try to get a recurring payment with the specified id
            var payment = _orderService.GetRecurringPaymentById(model.Id);
            if (payment == null || payment.Deleted)
                return RedirectToAction("List");

            if (ModelState.IsValid)
            {
                payment = model.ToEntity(payment);
                _orderService.UpdateRecurringPayment(payment);

                _notificationService.SuccessNotification(_localizationService.GetResource("Admin.RecurringPayments.Updated"));

                if (!continueEditing)
                    return RedirectToAction("List");
                
                return RedirectToAction("Edit", new { id = payment.Id });
            }

            //prepare model
            model = _recurringPaymentModelFactory.PrepareRecurringPaymentModel(model, payment, true);

            //if we got this far, something failed, redisplay form
            return View(model);
        }

        [HttpPost]
        public virtual IActionResult Delete(int id)
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageRecurringPayments))
                return AccessDeniedView();

            //try to get a recurring payment with the specified id
            var payment = _orderService.GetRecurringPaymentById(id);
            if (payment == null)
                return RedirectToAction("List");

            _orderService.DeleteRecurringPayment(payment);

            _notificationService.SuccessNotification(_localizationService.GetResource("Admin.RecurringPayments.Deleted"));

            return RedirectToAction("List");
        }

        [HttpPost]
        public virtual IActionResult HistoryList(RecurringPaymentHistorySearchModel searchModel)
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageRecurringPayments))
                return AccessDeniedDataTablesJson();

            //try to get a recurring payment with the specified id
            var payment = _orderService.GetRecurringPaymentById(searchModel.RecurringPaymentId)
                ?? throw new ArgumentException("No recurring payment found with the specified id");

            //prepare model
            var model = _recurringPaymentModelFactory.PrepareRecurringPaymentHistoryListModel(searchModel, payment);

            return Json(model);
        }

        [HttpPost, ActionName("Edit")]
        [FormValueRequired("processnextpayment")]
        public virtual IActionResult ProcessNextPayment(int id)
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageRecurringPayments))
                return AccessDeniedView();

            //try to get a recurring payment with the specified id
            var payment = _orderService.GetRecurringPaymentById(id);
            if (payment == null)
                return RedirectToAction("List");

            try
            {
                var errors = _orderProcessingService.ProcessNextRecurringPayment(payment).ToList();
                if (errors.Any())
                    errors.ForEach(error => _notificationService.ErrorNotification(error));
                else
                    _notificationService.SuccessNotification(_localizationService.GetResource("Admin.RecurringPayments.NextPaymentProcessed"));

                //prepare model
                var model = _recurringPaymentModelFactory.PrepareRecurringPaymentModel(null, payment);

                //selected panel
                SaveSelectedPanelName("recurringpayment-history", persistForTheNextRequest: false);

                return View(model);
            }
            catch (Exception exc)
            {
                _notificationService.ErrorNotification(exc);

                //prepare model
                var model = _recurringPaymentModelFactory.PrepareRecurringPaymentModel(null, payment);

                //selected panel
                SaveSelectedPanelName("recurringpayment-history", persistForTheNextRequest: false);

                return View(model);
            }
        }

        [HttpPost, ActionName("Edit")]
        [FormValueRequired("cancelpayment")]
        public virtual IActionResult CancelRecurringPayment(int id)
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageRecurringPayments))
                return AccessDeniedView();

            //try to get a recurring payment with the specified id
            var payment = _orderService.GetRecurringPaymentById(id);
            if (payment == null)
                return RedirectToAction("List");

            try
            {
                var errors = _orderProcessingService.CancelRecurringPayment(payment);
                if (errors.Any())
                {
                    foreach (var error in errors)
                        _notificationService.ErrorNotification(error);
                }
                else
                    _notificationService.SuccessNotification(_localizationService.GetResource("Admin.RecurringPayments.Cancelled"));

                //prepare model
                var model = _recurringPaymentModelFactory.PrepareRecurringPaymentModel(null, payment);

                //selected panel
                SaveSelectedPanelName("recurringpayment-history", persistForTheNextRequest: false);

                return View(model);
            }
            catch (Exception exc)
            {
                _notificationService.ErrorNotification(exc);

                //prepare model
                var model = _recurringPaymentModelFactory.PrepareRecurringPaymentModel(null, payment);

                //selected panel
                SaveSelectedPanelName("recurringpayment-history", persistForTheNextRequest: false);

                return View(model);
            }
        }

        #endregion
    }
}

src/Presentation/Nop.Web/Areas/Admin/Views/RecurringPayment/Edit.cshtml
@model RecurringPaymentModel

@{
    //page title
    ViewBag.Title = T("Admin.RecurringPayments.EditPaymentDetails").Text;
    //active menu item (system name)
    Html.SetActiveMenuItemSystemName("Recurring payments");
}

<form asp-controller="RecurringPayment" asp-action="Edit" method="post">
    <div class="content-header clearfix">
        <h1 class="pull-left">
            @T("Admin.RecurringPayments.EditPaymentDetails")
            <small>
                <i class="fa fa-arrow-circle-left"></i>
                <a asp-action="List">@T("Admin.RecurringPayments.BackToList")</a>
            </small>
        </h1>
        <div class="pull-right">
            <button type="submit" name="save" class="btn bg-blue">
                <i class="fa fa-floppy-o"></i>
                @T("Admin.Common.Save")
            </button>
            <button type="submit" name="save-continue" class="btn bg-blue">
                <i class="fa fa-floppy-o"></i>
                @T("Admin.Common.SaveContinue")
            </button>
            <span id="payment-delete" class="btn bg-red">
                <i class="fa fa-trash-o"></i>
                @T("Admin.Common.Delete")
            </span>
            @await Component.InvokeAsync("AdminWidget", new { widgetZone = AdminWidgetZones.ReccuringPaymentDetailsButtons, additionalData = Model })
        </div>
    </div>
    @await Html.PartialAsync("_CreateOrUpdate", Model)
</form>
<nop-delete-confirmation asp-model-id="@Model.Id" asp-button-id="payment-delete" />

src/Presentation/Nop.Web/Areas/Admin/Views/RecurringPayment/List.cshtml
@model RecurringPaymentSearchModel

@{
    //page title
    ViewBag.Title = T("Admin.RecurringPayments").Text;
    //active menu item (system name)
    Html.SetActiveMenuItemSystemName("Recurring payments");
}

<nop-antiforgery-token />
<div class="content-header clearfix">
    <h1 class="pull-left">
        @T("Admin.RecurringPayments")
    </h1>
    <div class="pull-right">
        &nbsp;
        @await Component.InvokeAsync("AdminWidget", new { widgetZone = AdminWidgetZones.ReccuringPaymentListButtons })
    </div>
</div>

<div class="content">
    <div class="form-horizontal">
        <div class="panel-group">
            <div class="panel panel-default">
                <div class="panel-body">
                    <p>
                        @T("Admin.RecurringPayments.Description")
                    </p>
                    @await Html.PartialAsync("Table", new DataTablesModel
                    {
                        Name = "recurringpayments-grid",
                        UrlRead = new DataUrl("List", "RecurringPayment", null),
                        Length = Model.PageSize,
                        LengthMenu = Model.AvailablePageSizes,
                        ColumnCollection = new List<ColumnProperty>
                        {
                            new ColumnProperty(nameof(RecurringPaymentModel.Id))
                            {
                                Title = T("Admin.RecurringPayments.Fields.ID").Text,
                                Width = "50"
                            },
                            new ColumnProperty(nameof(RecurringPaymentModel.CustomerId))
                            {
                                Title = T("Admin.RecurringPayments.Fields.Customer").Text,
                                Width = "200",
                                Render = new RenderCustom("renderColumnCustomerInfo")
                            },
                            new ColumnProperty(nameof(RecurringPaymentModel.CycleLength))
                            {
                                Title = T("Admin.RecurringPayments.Fields.CycleLength").Text,
                                Width = "100"
                            },
                            new ColumnProperty(nameof(RecurringPaymentModel.CyclePeriodStr))
                            {
                                Title = T("Admin.RecurringPayments.Fields.CyclePeriod").Text,
                                Width = "100"
                            },
                            new ColumnProperty(nameof(RecurringPaymentModel.IsActive))
                            {
                                Title = T("Admin.RecurringPayments.Fields.IsActive").Text,
                                Width = "200",
                                ClassName = NopColumnClassDefaults.CenterAll,
                                Render = new RenderBoolean()
                            },
                            new ColumnProperty(nameof(RecurringPaymentModel.StartDate))
                            {
                                Title = T("Admin.RecurringPayments.Fields.StartDate").Text,
                                Width = "200"
                            },
                            new ColumnProperty(nameof(RecurringPaymentModel.NextPaymentDate))
                            {
                                Title = T("Admin.RecurringPayments.Fields.NextPaymentDate").Text,
                                Width = "200"
                            },
                            new ColumnProperty(nameof(RecurringPaymentModel.TotalCycles))
                            {
                                Title = T("Admin.RecurringPayments.Fields.TotalCycles").Text,
                                Width = "100"
                            },
                            new ColumnProperty(nameof(RecurringPaymentModel.CyclesRemaining))
                            {
                                Title = T("Admin.RecurringPayments.Fields.CyclesRemaining").Text,
                                Width = "100"
                            },
                            new ColumnProperty(nameof(RecurringPaymentModel.Id))
                            {
                                Title = T("Admin.Common.Edit").Text,
                                Width = "100",
                                ClassName = NopColumnClassDefaults.Button,
                                Render = new RenderButtonEdit(new DataUrl("Edit"))
                            }
                        }
                    })
                    
                    <script>
                        function renderColumnCustomerInfo(data, type, row, meta) {
                            var textRenderer = $.fn.dataTable.render.text().display;
                            return '<a href="@Url.Content("~/Admin/Customer/Edit/")' + row.CustomerId + '">' + textRenderer(row.CustomerEmail) + '</a>';
                        }
                    </script>
                </div>
            </div>
        </div>
    </div>
</div>

src/Presentation/Nop.Web/Areas/Admin/Views/RecurringPayment/_CreateOrUpdate.History.cshtml
@model RecurringPaymentModel

<div class="panel-body">
    @if (Model.LastPaymentFailed)
    {
        <div class="form-group">
            <div class="col-md-12">
                @T("Admin.RecurringPayments.History.LastPaymentFailed")
            </div>
        </div>
    }
    @if (!string.IsNullOrEmpty(Model.NextPaymentDate))
    {
        <div class="form-group">
            <div class="col-md-12">
                @T("Admin.RecurringPayments.History.NextPaymentDate")
                <text>:</text>
                @Model.NextPaymentDate
            </div>
        </div>
    }
    @if (!string.IsNullOrEmpty(Model.NextPaymentDate) || Model.CanCancelRecurringPayment)
    {
        <div class="form-group">
            <div class="col-md-12">
                @if (!string.IsNullOrEmpty(Model.NextPaymentDate))
                {
                    <button type="submit" name="processnextpayment" class="btn bg-green">
                        @T("Admin.RecurringPayments.History.ProcessNextPayment")
                    </button>
                }
                @if (Model.CanCancelRecurringPayment)
                {
                    <button type="submit" name="cancelpayment" class="btn bg-navy">
                        @T("Admin.RecurringPayments.History.CancelPayment")
                    </button>
                }
            </div>
        </div>
    }

    @await Html.PartialAsync("Table", new DataTablesModel
    {
        Name = "history-grid",
        UrlRead = new DataUrl("HistoryList", "RecurringPayment", new RouteValueDictionary { [nameof(Model.RecurringPaymentHistorySearchModel.RecurringPaymentId)] = Model.RecurringPaymentHistorySearchModel.RecurringPaymentId }),
        Length = Model.RecurringPaymentHistorySearchModel.PageSize,
        LengthMenu = Model.RecurringPaymentHistorySearchModel.AvailablePageSizes,
        ColumnCollection = new List<ColumnProperty>
        {
            new ColumnProperty(nameof(RecurringPaymentHistoryModel.CustomOrderNumber))
            {
                Title = T("Admin.RecurringPayments.History.CustomOrderNumber").Text,
                ClassName =  NopColumnClassDefaults.Button,
                Width = "200",
                Render = new RenderCustom("renderColumnOrderInfo")
            },
            new ColumnProperty(nameof(RecurringPaymentHistoryModel.OrderStatus))
            {
                Title = T("Admin.RecurringPayments.History.OrderStatus").Text,
                Width = "200"
            },
            new ColumnProperty(nameof(RecurringPaymentHistoryModel.PaymentStatus))
            {
                Title = T("Admin.RecurringPayments.History.PaymentStatus").Text,
                Width = "200"
            },
            new ColumnProperty(nameof(RecurringPaymentHistoryModel.ShippingStatus))
            {
                Title = T("Admin.RecurringPayments.History.ShippingStatus").Text,
                Width = "200"
            },
            new ColumnProperty(nameof(RecurringPaymentHistoryModel.CreatedOn))
            {
                Title = T("Admin.RecurringPayments.History.CreatedOn").Text,
                Width = "100",
                Render = new RenderDate()
            }
        }
    })
    <script>
        function renderColumnOrderInfo(data, type, row, meta) {
            if (row.OrderId > 0) {
                var textRenderer = $.fn.dataTable.render.text().display;
                return '<a class="btn btn-default" href="@Url.Content("~/Admin/Order/Edit/")' + row.OrderId + '"><i class="fa fa-eye"></i>' + textRenderer(row.CustomOrderNumber) + ' - @T("Admin.Common.View")</a>';
            } else {
                return 'order item is deleted';
            }
        }
    </script>
</div>

src/Presentation/Nop.Web/Areas/Admin/Views/RecurringPayment/_CreateOrUpdate.Info.cshtml
@using Nop.Core.Domain.Catalog
@using Nop.Services
@model RecurringPaymentModel


<div class="panel-body">
    <div class="form-group">
        <div class="col-md-3">
            <nop-label asp-for="InitialOrderId" />
        </div>
        <div class="col-md-9">
            <a asp-controller="Order" asp-action="Edit" asp-route-id="@Model.InitialOrderId">@T("Admin.Common.View")</a>
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-3">
            <nop-label asp-for="CustomerEmail" />
        </div>
        <div class="col-md-9">
            <a asp-controller="Customer" asp-action="Edit" asp-route-id="@Model.CustomerId">@Model.CustomerEmail</a>
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-3">
            <nop-label asp-for="CycleLength" />
        </div>
        <div class="col-md-9">
            <nop-editor asp-for="CycleLength" />
            <span asp-validation-for="CycleLength"></span>
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-3">
            <nop-label asp-for="CyclePeriodId" />
        </div>
        <div class="col-md-9">
            <nop-select asp-for="CyclePeriodId" asp-items="@(((RecurringProductCyclePeriod)Model.CyclePeriodId).ToSelectList())" />
            <span asp-validation-for="CyclePeriodId"></span>
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-3">
            <nop-label asp-for="TotalCycles" />
        </div>
        <div class="col-md-9">
            <nop-editor asp-for="TotalCycles" />
            <span asp-validation-for="TotalCycles"></span>
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-3">
            <nop-label asp-for="CyclesRemaining" />
        </div>
        <div class="col-md-9">
            <div class="form-text-row">@Model.CyclesRemaining</div>
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-3">
            <nop-label asp-for="PaymentType" />
        </div>
        <div class="col-md-9">
            <div class="form-text-row">@Model.PaymentType</div>
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-3">
            <nop-label asp-for="StartDate" />
        </div>
        <div class="col-md-9">
            <div class="form-text-row">@Model.StartDate</div>
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-3">
            <nop-label asp-for="IsActive" />
        </div>
        <div class="col-md-9">
            <nop-editor asp-for="IsActive" />
            <span asp-validation-for="IsActive"></span>
        </div>
    </div>
</div>

src/Presentation/Nop.Web/Areas/Admin/Views/RecurringPayment/_CreateOrUpdate.cshtml
@model RecurringPaymentModel

@{
    const string hideInfoBlockAttributeName = "RecurringPaymentPage.HideInfoBlock";
    var hideInfoBlock = genericAttributeService.GetAttribute<bool>(workContext.CurrentCustomer, hideInfoBlockAttributeName);

    const string hideHistoryBlockAttributeName = "RecurringPaymentPage.HideHistoryBlock";
    var hideHistoryBlock = genericAttributeService.GetAttribute<bool>(workContext.CurrentCustomer, hideHistoryBlockAttributeName, defaultValue: true);
}

<div asp-validation-summary="All"></div>
<input asp-for="Id" type="hidden" />

<div class="content">
    <div class="form-horizontal">
        <nop-panels id="recurringpayment-edit">
            <nop-panel asp-name="recurringpayment-info" asp-icon="fa fa-info" asp-title="@T("Admin.RecurringPayments.Info")" asp-hide-block-attribute-name="@hideInfoBlockAttributeName" asp-hide="@hideInfoBlock">@await Html.PartialAsync("_CreateOrUpdate.Info", Model)</nop-panel>
            <nop-panel asp-name="recurringpayment-history" asp-icon="fa fa-history" asp-title="@T("Admin.RecurringPayments.History")" asp-hide-block-attribute-name="@hideHistoryBlockAttributeName" asp-hide="@hideHistoryBlock">@await Html.PartialAsync("_CreateOrUpdate.History", Model)</nop-panel>
                    
            @await Component.InvokeAsync("AdminWidget", new { widgetZone = AdminWidgetZones.ReccuringPaymentDetailBlock, additionalData = Model })
        </nop-panels>
    </div>
</div>